### ISSUE TITLE
Can you provide the rebuild binary that you used in readme? 

### ISSUE THREAD

**Issue by surajmandalcell** [redpfire/we#2]
I tried to compile it myself but getting longass errors related to boost linking (boost is installed btw).

**Comment by redpfire** [comment]
Hi! Thanks for reporting the issue. May i ask what distro are you using and did you install all libraries i specified?

**Comment by redpfire** [comment]
I just cloned the repo on my server and built it without any issues. Make sure to use `make linux`.

**Comment by redpfire** [comment]
Anyway - here is the binary 
`curl http://0x0.st/swwH.so > we`

sha256 checksum: 
`5c8680918fef4c133a40d24599369a46792df03ff03756d68d5741094602fa72`
