### ISSUE TITLE
It works at Mac

### ISSUE THREAD

**Issue by nowindowsguy1677** [redpfire/we#4]
Hey! I tried it in Mac system and It works!
1. install Xcode and the Xcode Command Line Tools

2. install libboost : `brew install boost` or `sudo port install boost`

2-1. If you don't have brew : `ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" < /dev/null 2> /dev/null`

2-2. If you don't have Macport : Install [Macport](https://www.macports.org/) and reboot.

3. `make linux`

4. `./we x scene.pkg`

5. `./we r scene.pkg`

**Comment by redpfire** [comment]
Brilliant! Could you please add this as a section to the readme and make a Pull Request?
