### ISSUE TITLE
How to build on Ubuntu

### ISSUE THREAD

**Issue by Matias-Louzao-Ataria** [redpfire/we#8]
g++ -lboost_system -lboost_filesystem --std=c++11 -o we *.cpp
/tmp/ccBbjCDw.o: En la función `__static_initialization_and_destruction_0(int, int)':
main.cpp:(.text+0x162c): referencia a `boost::system::generic_category()' sin definir
main.cpp:(.text+0x1638): referencia a `boost::system::generic_category()' sin definir
main.cpp:(.text+0x1644): referencia a `boost::system::system_category()' sin definir
/tmp/ccBbjCDw.o: En la función `boost::system::error_code::error_code()':
main.cpp:(.text._ZN5boost6system10error_codeC2Ev[_ZN5boost6system10error_codeC5Ev]+0x17): referencia a `boost::system::system_category()' sin definir
/tmp/ccBbjCDw.o: En la función `boost::system::error_code::clear()':
main.cpp:(.text._ZN5boost6system10error_code5clearEv[_ZN5boost6system10error_code5clearEv]+0x17): referencia a `boost::system::system_category()' sin definir
/tmp/ccBbjCDw.o: En la función `boost::system::error_category::std_category::equivalent(int, std::error_condition const&) const':
main.cpp:(.text._ZNK5boost6system14error_category12std_category10equivalentEiRKSt15error_condition[_ZNK5boost6system14error_category12std_category10equivalentEiRKSt15error_condition]+0xb8): referencia a `boost::system::generic_category()' sin definir
main.cpp:(.text._ZNK5boost6system14error_category12std_category10equivalentEiRKSt15error_condition[_ZNK5boost6system14error_category12std_category10equivalentEiRKSt15error_condition]+0xf3): referencia a `boost::system::generic_category()' sin definir
/tmp/ccBbjCDw.o: En la función `boost::system::error_category::std_category::equivalent(std::error_code const&, int) const':
main.cpp:(.text._ZNK5boost6system14error_category12std_category10equivalentERKSt10error_codei[_ZNK5boost6system14error_category12std_category10equivalentERKSt10error_codei]+0xb8): referencia a `boost::system::generic_category()' sin definir
main.cpp:(.text._ZNK5boost6system14error_category12std_category10equivalentERKSt10error_codei[_ZNK5boost6system14error_category12std_category10equivalentERKSt10error_codei]+0xf3): referencia a `boost::system::generic_category()' sin definir
main.cpp:(.text._ZNK5boost6system14error_category12std_category10equivalentERKSt10error_codei[_ZNK5boost6system14error_category12std_category10equivalentERKSt10error_codei]+0x1d2): referencia a `boost::system::generic_category()' sin definir
/tmp/ccBbjCDw.o: En la función `boost::filesystem::is_directory(boost::filesystem::path const&)':
main.cpp:(.text._ZN5boost10filesystem12is_directoryERKNS0_4pathE[_ZN5boost10filesystem12is_directoryERKNS0_4pathE]+0x2f): referencia a `boost::filesystem::detail::status(boost::filesystem::path const&, boost::system::error_code*)' sin definir
/tmp/ccBbjCDw.o: En la función `boost::filesystem::create_directories(boost::filesystem::path const&)':
main.cpp:(.text._ZN5boost10filesystem18create_directoriesERKNS0_4pathE[_ZN5boost10filesystem18create_directoriesERKNS0_4pathE]+0x19): referencia a `boost::filesystem::detail::create_directories(boost::filesystem::path const&, boost::system::error_code*)' sin definir
/tmp/ccBbjCDw.o: En la función `boost::filesystem::file_size(boost::filesystem::path const&)':
main.cpp:(.text._ZN5boost10filesystem9file_sizeERKNS0_4pathE[_ZN5boost10filesystem9file_sizeERKNS0_4pathE]+0x19): referencia a `boost::filesystem::detail::file_size(boost::filesystem::path const&, boost::system::error_code*)' sin definir
/tmp/ccBbjCDw.o: En la función `boost::filesystem::remove_all(boost::filesystem::path const&)':
main.cpp:(.text._ZN5boost10filesystem10remove_allERKNS0_4pathE[_ZN5boost10filesystem10remove_allERKNS0_4pathE]+0x19): referencia a `boost::filesystem::detail::remove_all(boost::filesystem::path const&, boost::system::error_code*)' sin definir
/tmp/ccBbjCDw.o: En la función `boost::filesystem::directory_entry::status(boost::system::error_code&) const':
main.cpp:(.text._ZNK5boost10filesystem15directory_entry6statusERNS_6system10error_codeE[_ZNK5boost10filesystem15directory_entry6statusERNS_6system10error_codeE]+0x36): referencia a `boost::filesystem::directory_entry::m_get_status(boost::system::error_code*) const' sin definir
/tmp/ccBbjCDw.o: En la función `boost::filesystem::directory_entry::symlink_status(boost::system::error_code&) const':
main.cpp:(.text._ZNK5boost10filesystem15directory_entry14symlink_statusERNS_6system10error_codeE[_ZNK5boost10filesystem15directory_entry14symlink_statusERNS_6system10error_codeE]+0x36): referencia a `boost::filesystem::directory_entry::m_get_symlink_status(boost::system::error_code*) const' sin definir
/tmp/ccBbjCDw.o: En la función `boost::filesystem::detail::dir_itr_imp::~dir_itr_imp()':
main.cpp:(.text._ZN5boost10filesystem6detail11dir_itr_impD2Ev[_ZN5boost10filesystem6detail11dir_itr_impD5Ev]+0x24): referencia a `boost::filesystem::detail::dir_itr_close(void*&, void*&)' sin definir
/tmp/ccBbjCDw.o: En la función `boost::filesystem::directory_iterator::directory_iterator(boost::filesystem::path const&)':
main.cpp:(.text._ZN5boost10filesystem18directory_iteratorC2ERKNS0_4pathE[_ZN5boost10filesystem18directory_iteratorC5ERKNS0_4pathE]+0x4b): referencia a `boost::filesystem::detail::directory_iterator_construct(boost::filesystem::directory_iterator&, boost::filesystem::path const&, boost::system::error_code*)' sin definir
/tmp/ccBbjCDw.o: En la función `boost::filesystem::directory_iterator::directory_iterator(boost::filesystem::path const&, boost::system::error_code&)':
main.cpp:(.text._ZN5boost10filesystem18directory_iteratorC2ERKNS0_4pathERNS_6system10error_codeE[_ZN5boost10filesystem18directory_iteratorC5ERKNS0_4pathERNS_6system10error_codeE]+0x4e): referencia a `boost::filesystem::detail::directory_iterator_construct(boost::filesystem::directory_iterator&, boost::filesystem::path const&, boost::system::error_code*)' sin definir
/tmp/ccBbjCDw.o: En la función `boost::filesystem::directory_iterator::increment()':
main.cpp:(.text._ZN5boost10filesystem18directory_iterator9incrementEv[_ZN5boost10filesystem18directory_iterator9incrementEv]+0x19): referencia a `boost::filesystem::detail::directory_iterator_increment(boost::filesystem::directory_iterator&, boost::system::error_code*)' sin definir
collect2: error: ld returned 1 exit status
Makefile:3: recipe for target 'linux' failed
make: *** [linux] Error 1

**Comment by redpfire** [comment]
Did you even install boost?

**Comment by Matias-Louzao-Ataria** [comment]
Yeah, I have boost installed

**Comment by coldreactor64** [comment]
I fixed this issue for myself by just changing the make file so its `g++  --std=c++11 -o we _.cpp_ -lboost_system -lboost_filesystem` And that fixed the problem easily and compiled.

**Comment by Motyak** [comment]
I had the same issue, I changed the command line by '$g++ -o we main.cpp -lboost_system -lboost_filesystem --std=c++11' and it fixed it.
You can also install libboost with '$sudo apt-get install libboost-all-dev' if you don't want to install brew.
